apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
    webhook:
      github:
        endpoint: /push
        port: "12000"
        method: POST 
 