apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  gitlab:
    example:
      projects:
        - "kaan0015/argocd-test-repo"
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://github.com/kaan0015/argocd-test-repo.git
      events:
        - close
        - merge
        - "*"
      webhookSecret:
        name: https://github.com/kaan0015/argocd-test-repo.git
        key: fenerbahce
      insecure: true
      active: true
      contentType: "json"