apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mr-undeploy 
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: github
    eventName: example
  triggers:
  - template:
      name: payload
      k8s:
        operation: delete
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              labels:
                app.kubernetes.io/instance: asdf
              name: asdf
              namespace: argo-events
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.message
            dest: metadata.name
            operation: append