apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mr-undeploy
spec:
  dependencies:
  - name: mr-close
    eventSourceName: github
    eventName: example
  triggers:
  - template:
      conditions: "mr-close"
      name: mr-undeploy
      k8s:
        operation: delete
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: asdfff
              namespace: argocd
        parameters:
        - src:
            dependencyName: mr-close
            dataKey: body.message
          dest: metadata.name
          