apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
  - name: mr-close
    eventSourceName: github
    eventName: example
    filters:
      data:
      - path: body.X-GitHub-Event
        type: string
        value:
        - "*"
  triggers:
  - template:
      name: github-workflow-trigger
      k8s:
        operation: delete
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Application 
            metadata:
              name: nginx
        parameters:
        - src: 
            dependencyName: mr-close
            dataTemplate: "{{ .Input.body.pull_request.head.sha | substr 0 7 }}"
          dest: metadata.name
      retryStrategy:
        steps: 3