apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mr-undeploy 
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: github
    eventName: example
  triggers:
  - template:
      name: payload
      k8s:
        operation: delete
        resource: Application
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: asdf
              namespace: argo-events
            spec:
              destination:
                namespace: argo-events
                server: https://kubernetes.default.svc
              project: default
              source:
                path: argo_cd_yaml_files/
                repoURL: https://github.com/kaan0015/argocd-test-repo.git
                targetRevision: yeni
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.message
            dest: spec.containers.0.args.1