apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
  - name: mr-close
    eventSourceName: github
    eventName: example
    filters:
      data:
      - path: body.X-GitHub-Event
        type: string
        value:
        - "*"
      - path: body.action
        type: string
        value:
          - opened
          - edited
          - reopened
          - synchronize
      - path: body.pull_request.state
        type: string
        value:
          - open
      - path: body.pull_request.base.ref
        type: string
        value:
          - master
  triggers:
  - template:
      name: github-workflow-trigger
      k8s:
        operation: delete
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Application 
            metadata:
              name: asdf
        parameters:
        - src:   
            dependencyName: mr-close 
            dataKey: body.pull_request.title
            dataTemplate: "{{ .Input.body.pull_request.head.sha | substr 0 7 }}"
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: mr-close
            dataKey: body.pull_request.number
          dest: spec.arguments.parameters.1.value
        - src:
            dependencyName: mr-close
            dataTemplate: "{{ .Input.body.pull_request.head.sha | substr 0 7 }}"
          dest: spec.arguments.parameters.2.value
        - src:
            dependencyName: mr-close
            dataTemplate: "{{ .Input.body.pull_request.number }}-{{ .Input.body.pull_request.head.sha | substr 0 7 }}"
          dest: metadata.name
      retryStrategy:
        steps: 3