apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mr-deploy
spec:
  dependencies:
  - name: mr-open
    eventSourceName: github
    eventName: example
    filters:
      data:
      - path: body.object_attributes.action
        type: string
        value:
        - "open"
        - "reopen"
        - "update"
  triggers:
  - template:
      conditions: "mr-open"
      name: mr-deploy
      k8s:
        operation: create
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: dyn-tmpl
              namespace: argocd
            spec:
              project: apps
              source:
                repoURL: 'https://github.com/kaan0015/argocd-test-repo.git'
                targetRevision: "HEAD"
                path: "deployments/dyn-website/"
                helm:
                  values: "MR: wrong"
              destination:
                namespace: default
                server: 'https://kubernetes.default.svc'
              syncPolicy:
                automated: {}
                syncOptions:
                  - CreateNamespace=true
        parameters:
        - src:
            dependencyName: mr-open
            dataTemplate: "MR: {{ .Input.body.object_attributes.iid }}"
          dest: spec.source.helm.values
        - src:
            dependencyName: mr-open
            dataTemplate: "dyn-website-mr-{{ .Input.body.object_attributes.iid }}"
          dest: metadata.name
        - src:
            dependencyName: mr-open
            dataKey: body.message
          dest: spec.containers.0.args.1
          
      